"""
Page 33: Clinical Report Generator
====================================

Generate a comprehensive one-page clinical report from the digital twin
analysis. Summarizes genomic findings, treatment recommendations, and
neoantigen vaccine candidates in a format suitable for clinical review.
"""

import streamlit as st
from cognisom.dashboard.page_config import safe_set_page_config

safe_set_page_config(page_title="Clinical Report | Cognisom", page_icon="\U0001f4cb", layout="wide")

from cognisom.auth.middleware import streamlit_page_gate
user = streamlit_page_gate("33_clinical_report")

import json
from datetime import datetime

st.title("Clinical Report Generator")
st.caption("Generate a comprehensive genomic analysis report from the digital twin pipeline.")

# Check for patient data
profile = st.session_state.get("patient_profile")

if profile is None:
    st.warning(
        "No patient profile loaded. Complete the **Genomic Profile** (page 26) first, "
        "then return here to generate the clinical report."
    )
    st.stop()

# ── Report Header ────────────────────────────────────────────────

st.markdown("---")

st.markdown(f"""
<div style="background: linear-gradient(135deg, rgba(99,102,241,0.1), rgba(99,102,241,0.05));
            border: 1px solid rgba(99,102,241,0.3); border-radius: 12px;
            padding: 1.5rem; margin-bottom: 1rem;">
    <div style="display: flex; justify-content: space-between; align-items: center;">
        <div>
            <div style="font-size: 1.5rem; font-weight: 700;">Cognisom Genomic Analysis Report</div>
            <div style="font-size: 0.85rem; opacity: 0.6;">Personalized Molecular Digital Twin Platform</div>
        </div>
        <div style="text-align: right;">
            <div style="font-size: 0.85rem;"><strong>Patient ID:</strong> {profile.patient_id}</div>
            <div style="font-size: 0.85rem;"><strong>Cancer Type:</strong> {profile.cancer_type.title()}</div>
            <div style="font-size: 0.85rem;"><strong>Date:</strong> {datetime.now().strftime('%Y-%m-%d')}</div>
        </div>
    </div>
</div>
""", unsafe_allow_html=True)

# Beta disclaimer
st.markdown(
    '<div style="background: rgba(234,88,12,0.1); border: 1px solid rgba(234,88,12,0.3); '
    'border-radius: 6px; padding: 0.5rem 0.8rem; font-size: 0.75rem; margin-bottom: 1rem;">'
    '<strong style="color: #f97316;">RESEARCH USE ONLY</strong> — '
    'This report is generated by computational analysis and is not validated for clinical '
    'decision-making. Results should be reviewed by qualified medical professionals.</div>',
    unsafe_allow_html=True,
)

# ── Section 1: Genomic Summary ───────────────────────────────────

st.markdown("### 1. Genomic Summary")

m1, m2, m3, m4 = st.columns(4)
m1.metric("Total Variants", len(profile.variants))
m2.metric("Cancer Drivers", len(profile.cancer_driver_mutations))
m3.metric("TMB", f"{profile.tumor_mutational_burden:.1f} mut/Mb",
          delta="High" if profile.is_tmb_high else "Low")
m4.metric("MSI Status", profile.msi_status)

if profile.cancer_driver_mutations:
    st.markdown("**Cancer Driver Mutations:**")
    drivers = profile.get_driver_details()
    for d in drivers:
        impact_color = "#ef4444" if d["impact"] == "HIGH" else (
            "#f59e0b" if d["impact"] == "MODERATE" else "#6b7280")
        st.markdown(
            f'- **{d["gene"]}** {d["mutation"]} — '
            f'<span style="color: {impact_color};">{d["impact"]}</span> '
            f'({d["role"]}) — {d["clinical_significance"][:80]}',
            unsafe_allow_html=True,
        )

# ── Section 2: HLA Type & Neoantigens ───────────────────────────

st.markdown("### 2. HLA Typing & Neoantigen Analysis")

c1, c2 = st.columns(2)

with c1:
    if profile.hla_alleles:
        from cognisom.genomics.hla_typer import HLATyper
        st.markdown(f"**HLA Type:** {HLATyper.format_alleles(profile.hla_alleles)}")
    else:
        st.markdown("**HLA Type:** Not determined")

    neo_count = len(profile.predicted_neoantigens)
    vaccine_count = len(profile.vaccine_neoantigens)
    strong = profile.strong_binder_count

    st.markdown(f"""
    - **Predicted neoantigens:** {neo_count}
    - **Strong MHC-I binders (<50 nM):** {strong}
    - **Vaccine candidates:** {vaccine_count}
    - **Vaccine eligible:** {'Yes' if profile.neoantigen_vaccine_candidate else 'No'}
    """)

with c2:
    if profile.vaccine_neoantigens:
        st.markdown("**Top Vaccine Targets:**")
        for n in profile.vaccine_neoantigens[:5]:
            st.markdown(
                f"- `{n.peptide}` ({n.source_gene} {n.mutation}) → "
                f"{n.best_hla_allele} ({n.binding_affinity_nm:.0f} nM)"
            )

# ── Section 3: Treatment Recommendations ─────────────────────────

st.markdown("### 3. Treatment Recommendations")

recs = profile.get_therapy_recommendations()
if recs:
    for i, rec in enumerate(recs, 1):
        confidence_color = "#10b981" if rec["confidence"] == "high" else (
            "#f59e0b" if rec["confidence"] == "moderate" else "#6b7280")
        st.markdown(
            f'**{i}. {rec["therapy_class"]}** — '
            f'{", ".join(rec["drugs"][:3])}\n\n'
            f'&nbsp;&nbsp;&nbsp;&nbsp;'
            f'<span style="color: {confidence_color};">Confidence: {rec["confidence"]}</span> — '
            f'{rec["rationale"][:120]}',
            unsafe_allow_html=True,
        )
else:
    st.info("No specific therapy recommendations based on current genomic profile.")

# ── Section 4: Digital Twin Simulation ───────────────────────────

st.markdown("### 4. Digital Twin Treatment Simulation")

try:
    from cognisom.library.store import EntityStore
    from cognisom.genomics.twin_config import DigitalTwinConfig
    from cognisom.genomics.treatment_simulator import TreatmentSimulator

    twin = DigitalTwinConfig.from_profile_only(profile)
    store = EntityStore()
    sim = TreatmentSimulator(store=store)

    recommended = sim.get_recommended_treatments(twin)
    if recommended:
        import plotly.graph_objects as go

        results = sim.compare_treatments(recommended[:6], twin, 180)

        # Treatment comparison table
        st.markdown("**Simulated Treatment Response (180 days):**")

        for r in results:
            response_color = {
                "CR": "#10b981", "PR": "#3b82f6", "SD": "#f59e0b", "PD": "#ef4444"
            }.get(r.response_category, "#6b7280")

            reduction = (1 - r.best_response) * 100

            st.markdown(
                f'- **{r.treatment_name}**: '
                f'<span style="color: {response_color}; font-weight: 700;">'
                f'{r.response_category}</span> '
                f'({reduction:.0f}% reduction) — '
                f'PFS: {r.progression_free_days}d — '
                f'irAE risk: {r.immune_related_adverse_events:.0%}',
                unsafe_allow_html=True,
            )

        # Tumor response curves
        fig = go.Figure()
        for r in results:
            fig.add_trace(go.Scatter(
                y=r.tumor_response_curve,
                mode="lines",
                name=f"{r.treatment_name} ({r.response_category})",
                line=dict(width=2),
            ))
        fig.add_hline(y=0.7, line_dash="dash", line_color="gray",
                      annotation_text="PR threshold (30% reduction)")
        fig.update_layout(
            title="Tumor Response Curves",
            xaxis_title="Days",
            yaxis_title="Relative Tumor Volume",
            height=350,
            legend=dict(font=dict(size=9)),
        )
        st.plotly_chart(fig, use_container_width=True)

except Exception as e:
    st.error(f"Treatment simulation failed: {e}")

# ── Section 5: Biomarker Summary ─────────────────────────────────

st.markdown("### 5. Actionable Biomarkers")

biomarkers = []
if profile.is_tmb_high:
    biomarkers.append(("TMB-High", f"{profile.tumor_mutational_burden:.1f} mut/Mb",
                        "Checkpoint inhibitor eligible (pembrolizumab, FDA-approved for TMB≥10)"))
if profile.msi_status == "MSI-H":
    biomarkers.append(("MSI-High", "MSI-H",
                        "Checkpoint inhibitor eligible (pembrolizumab, FDA-approved for MSI-H)"))
if profile.has_dna_repair_defect:
    repair_genes = [g for g in profile.affected_genes if g in {"BRCA1", "BRCA2", "ATM", "CDK12", "PALB2"}]
    biomarkers.append(("HRD", ", ".join(repair_genes),
                        "PARP inhibitor candidate (olaparib, FDA-approved for BRCA1/2 mCRPC)"))
if profile.has_ar_mutation:
    biomarkers.append(("AR Mutation", "Detected",
                        "Monitor for AR-targeted therapy resistance (enzalutamide, abiraterone)"))
if profile.neoantigen_vaccine_candidate:
    biomarkers.append(("Neoantigen-Rich", f"{len(profile.vaccine_neoantigens)} targets",
                        "Personalized mRNA vaccine candidate (mRNA-4157/V940 paradigm)"))

if biomarkers:
    for name, value, action in biomarkers:
        st.markdown(f"- **{name}**: {value} → {action}")
else:
    st.info("No actionable biomarkers identified in the current profile.")

# ── Export ────────────────────────────────────────────────────────

st.markdown("---")

col_export1, col_export2 = st.columns(2)

with col_export1:
    # JSON export
    report_data = {
        "report_type": "cognisom_genomic_analysis",
        "version": "1.0",
        "generated": datetime.now().isoformat(),
        "patient_id": profile.patient_id,
        "cancer_type": profile.cancer_type,
        "genomic_summary": {
            "total_variants": len(profile.variants),
            "cancer_drivers": len(profile.cancer_driver_mutations),
            "tmb": profile.tumor_mutational_burden,
            "msi_status": profile.msi_status,
            "tmb_high": profile.is_tmb_high,
            "dna_repair_defect": profile.has_dna_repair_defect,
        },
        "hla_alleles": profile.hla_alleles,
        "neoantigens": {
            "total_predicted": len(profile.predicted_neoantigens),
            "vaccine_candidates": len(profile.vaccine_neoantigens),
            "strong_binders": profile.strong_binder_count,
        },
        "driver_mutations": profile.get_driver_details(),
        "therapy_recommendations": profile.get_therapy_recommendations(),
        "disclaimer": "Research use only. Not for clinical decision-making.",
    }

    st.download_button(
        "Download Report (JSON)",
        data=json.dumps(report_data, indent=2, default=str),
        file_name=f"cognisom_report_{profile.patient_id}_{datetime.now().strftime('%Y%m%d')}.json",
        mime="application/json",
        use_container_width=True,
    )

with col_export2:
    # Text summary for clipboard
    summary_lines = [
        f"COGNISOM GENOMIC ANALYSIS REPORT",
        f"Patient: {profile.patient_id} | Cancer: {profile.cancer_type}",
        f"Date: {datetime.now().strftime('%Y-%m-%d')}",
        f"",
        f"GENOMIC SUMMARY:",
        f"  Variants: {len(profile.variants)} | Drivers: {len(profile.cancer_driver_mutations)}",
        f"  TMB: {profile.tumor_mutational_burden:.1f} mut/Mb ({'High' if profile.is_tmb_high else 'Low'})",
        f"  MSI: {profile.msi_status}",
        f"  HRD: {'Yes' if profile.has_dna_repair_defect else 'No'}",
        f"",
        f"DRIVER MUTATIONS:",
    ]
    for d in profile.get_driver_details():
        summary_lines.append(f"  {d['gene']} {d['mutation']} ({d['impact']}, {d['role']})")
    summary_lines.extend([
        f"",
        f"NEOANTIGENS: {len(profile.predicted_neoantigens)} predicted, "
        f"{len(profile.vaccine_neoantigens)} vaccine candidates",
        f"",
        f"RECOMMENDATIONS:",
    ])
    for rec in profile.get_therapy_recommendations():
        summary_lines.append(f"  {rec['therapy_class']}: {', '.join(rec['drugs'][:3])}")
    summary_lines.extend([
        f"",
        f"DISCLAIMER: Research use only. Not for clinical decision-making.",
    ])

    st.download_button(
        "Download Report (Text)",
        data="\n".join(summary_lines),
        file_name=f"cognisom_report_{profile.patient_id}.txt",
        mime="text/plain",
        use_container_width=True,
    )
