"""
MolMIM NIM Client
=================

Generate novel small molecules from a seed SMILES string.
Uses CMA-ES optimization to explore chemical space around a scaffold.
"""

import json
import logging
from dataclasses import dataclass
from typing import List, Optional

from .client import NIMClient

logger = logging.getLogger(__name__)

ENDPOINT = "nvidia/molmim/generate"


@dataclass
class GeneratedMolecule:
    """A molecule generated by MolMIM."""
    smiles: str
    score: float  # QED (Quantitative Estimate of Drug-likeness, 0-1)


class MolMIMClient(NIMClient):
    """Client for MolMIM molecule generation NIM.

    MolMIM generates novel small molecules by exploring chemical space
    around a seed molecule using CMA-ES optimization.

    Example:
        client = MolMIMClient()
        molecules = client.generate("CC(=O)Oc1ccccc1C(=O)O", num_molecules=5)
        for mol in molecules:
            print(f"{mol.smiles}  (QED: {mol.score:.3f})")
    """

    def generate(self, smiles: str, num_molecules: int = 10,
                 algorithm: str = "CMA-ES") -> List[GeneratedMolecule]:
        """Generate molecules from a seed SMILES.

        Args:
            smiles: Seed molecule in SMILES format.
            num_molecules: Number of molecules to generate.
            algorithm: Optimization algorithm (default CMA-ES).

        Returns:
            List of GeneratedMolecule with SMILES and QED scores.
        """
        result = self._post(ENDPOINT, {
            "smi": smiles,
            "num_molecules": num_molecules,
            "algorithm": algorithm,
        })

        raw = json.loads(result["molecules"])
        molecules = [
            GeneratedMolecule(smiles=m["sample"], score=m["score"])
            for m in raw
        ]
        logger.info(f"Generated {len(molecules)} molecules from {smiles}")
        return molecules

    def generate_for_target(self, seed_smiles: str, num_molecules: int = 20,
                            min_qed: float = 0.5) -> List[GeneratedMolecule]:
        """Generate and filter molecules by QED score.

        Generates molecules and returns only those above the QED threshold.
        Useful for drug discovery where you want drug-like candidates.

        Args:
            seed_smiles: Starting molecule SMILES.
            num_molecules: Number to generate (before filtering).
            min_qed: Minimum QED score to keep (0-1).

        Returns:
            Filtered list sorted by QED score (highest first).
        """
        molecules = self.generate(seed_smiles, num_molecules)
        filtered = [m for m in molecules if m.score >= min_qed]
        filtered.sort(key=lambda m: m.score, reverse=True)
        logger.info(f"Kept {len(filtered)}/{len(molecules)} with QED >= {min_qed}")
        return filtered
