"""
Reference CDS sequences for the gene library.

All three CDSes below are *authentic* NCBI reference sequences,
captured inline so the module imports without network access. The
canonical hotspots are validated against these sequences at import
time so any future corruption is caught immediately.

  KRAS  NM_004985.5  -- 567 bp / 188 aa (full CDS)
  TP53  NM_000546.6  -- 1182 bp / 393 aa (full CDS)
  BRAF  NM_004333.6  -- 2301 bp / 766 aa (full CDS)

Earlier revisions of this file carried synthetic CDSes for TP53 and
BRAF with a real first-30-codon prefix and GCG (Ala) filler to reach
the hotspot positions, marked VERIFY-BEFORE-FILING. That note is now
resolved: this revision replaces those placeholders with the
authentic CDSes fetched directly from NCBI via Biopython Entrez
(captured 2026-05-12 against the accessions above). The hotspot
positions, expected wild-type codons, and protein lengths all match
the synthetic placeholders bit-for-bit, so no downstream code or
test breaks.

Validation at import time:
  - start codon (ATG) at codon 1
  - canonical oncogenic hotspot codons at the expected positions
    (KRAS G12 = GGT, KRAS G13 = GGC, TP53 R175 = CGC, TP53 R248 = CGG,
     BRAF V600 = GTG)
  - exactly one stop codon, at the end
  - CDS length matches the published protein length + stop

Logged in DECISIONS.md alongside the prior 2026-05-11 synthetic-CDS
entry.
"""

from __future__ import annotations

from typing import Dict


# ---------------------------------------------------------------------------
# KRAS - NM_004985.5 (authentic, 567 bp / 188 aa + stop)
# ---------------------------------------------------------------------------

KRAS_CDS: str = (
    "ATGACTGAATATAAACTTGTGGTAGTTGGAGCTGGTGGCGTAGGCAAGAGTGCCTTGACG"
    "ATACAGCTAATTCAGAATCATTTTGTGGACGAATATGATCCAACAATAGAGGATTCCTAC"
    "AGGAAGCAAGTAGTAATTGATGGAGAAACCTGTCTCTTGGATATTCTCGACACAGCAGGT"
    "CAAGAGGAGTACAGTGCAATGAGGGACCAGTACATGAGGACTGGGGAGGGCTTTCTTTGT"
    "GTATTTGCCATAAATAATACTAAATCATTTGAAGATATTCACCATTATAGAGAACAAATT"
    "AAAAGAGTTAAGGACTCTGAAGATGTACCTATGGTCCTAGTAGGAAATAAATGTGATTTG"
    "CCTTCTAGAACAGTAGACACAAAACAGGCTCAGGACTTAGCAAGAAGTTATGGAATTCCT"
    "TTTATTGAAACATCAGCAAAGACAAGACAGGGTGTTGATGATGCCTTCTATACATTAGTT"
    "CGAGAAATTCGAAAACATAAAGAAAAGATGAGCAAAGATGGTAAAAAGAAGAAAAAGAAG"
    "TCAAAGACAAAGTGTGTAATTATGTAA"
)

KRAS_HOTSPOTS: Dict[int, str] = {
    11: "GGT",  # codon 12 (Gly) - G12D/G12V site
    12: "GGC",  # codon 13 (Gly) - G13D site
}


# ---------------------------------------------------------------------------
# TP53 - NM_000546.6 (authentic, 1182 bp / 393 aa + stop)
# ---------------------------------------------------------------------------

TP53_CDS: str = (
    "ATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCA"
    "GACCTATGGAAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATG"
    "GATGATTTGATGCTGTCCCCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCA"
    "GATGAAGCTCCCAGAATGCCAGAGGCTGCTCCCCCCGTGGCCCCTGCACCAGCAGCTCCT"
    "ACACCGGCGGCCCCTGCACCAGCCCCCTCCTGGCCCCTGTCATCTTCTGTCCCTTCCCAG"
    "AAAACCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCATTCTGGGACAGCCAAG"
    "TCTGTGACTTGCACGTACTCCCCTGCCCTCAACAAGATGTTTTGCCAACTGGCCAAGACC"
    "TGCCCTGTGCAGCTGTGGGTTGATTCCACACCCCCGCCCGGCACCCGCGTCCGCGCCATG"
    "GCCATCTACAAGCAGTCACAGCACATGACGGAGGTTGTGAGGCGCTGCCCCCACCATGAG"
    "CGCTGCTCAGATAGCGATGGTCTGGCCCCTCCTCAGCATCTTATCCGAGTGGAAGGAAAT"
    "TTGCGTGTGGAGTATTTGGATGACAGAAACACTTTTCGACATAGTGTGGTGGTGCCCTAT"
    "GAGCCGCCTGAGGTTGGCTCTGACTGTACCACCATCCACTACAACTACATGTGTAACAGT"
    "TCCTGCATGGGCGGCATGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCC"
    "AGTGGTAATCTACTGGGACGGAACAGCTTTGAGGTGCGTGTTTGTGCCTGTCCTGGGAGA"
    "GACCGGCGCACAGAGGAAGAGAATCTCCGCAAGAAAGGGGAGCCTCACCACGAGCTGCCC"
    "CCAGGGAGCACTAAGCGAGCACTGCCCAACAACACCAGCTCCTCTCCCCAGCCAAAGAAG"
    "AAACCACTGGATGGAGAATATTTCACCCTTCAGATCCGTGGGCGTGAGCGCTTCGAGATG"
    "TTCCGAGAGCTGAATGAGGCCTTGGAACTCAAGGATGCCCAGGCTGGGAAGGAGCCAGGG"
    "GGGAGCAGGGCTCACTCCAGCCACCTGAAGTCCAAAAAGGGTCAGTCTACCTCCCGCCAT"
    "AAAAAACTCATGTTCAAGACAGAAGGGCCTGACTCAGACTGA"
)

TP53_HOTSPOTS: Dict[int, str] = {
    174: "CGC",  # codon 175 (Arg) - R175H site (CGC -> CAC)
    247: "CGG",  # codon 248 (Arg) - R248W site (CGG -> TGG)
}


# ---------------------------------------------------------------------------
# BRAF - NM_004333.6 (authentic, 2301 bp / 766 aa + stop)
# ---------------------------------------------------------------------------

BRAF_CDS: str = (
    "ATGGCGGCGCTGAGCGGTGGCGGTGGTGGCGGCGCGGAGCCGGGCCAGGCTCTGTTCAAC"
    "GGGGACATGGAGCCCGAGGCCGGCGCCGGCGCCGGCGCCGCGGCCTCTTCGGCTGCGGAC"
    "CCTGCCATTCCGGAGGAGGTGTGGAATATCAAACAAATGATTAAGTTGACACAGGAACAT"
    "ATAGAGGCCCTATTGGACAAATTTGGTGGGGAGCATAATCCACCATCAATATATCTGGAG"
    "GCCTATGAAGAATACACCAGCAAGCTAGATGCACTCCAACAAAGAGAACAACAGTTATTG"
    "GAATCTCTGGGGAACGGAACTGATTTTTCTGTTTCTAGCTCTGCATCAATGGATACCGTT"
    "ACATCTTCTTCCTCTTCTAGCCTTTCAGTGCTACCTTCATCTCTTTCAGTTTTTCAAAAT"
    "CCCACAGATGTGGCACGGAGCAACCCCAAGTCACCACAAAAACCTATCGTTAGAGTCTTC"
    "CTGCCCAACAAACAGAGGACAGTGGTACCTGCAAGGTGTGGAGTTACAGTCCGAGACAGT"
    "CTAAAGAAAGCACTGATGATGAGAGGTCTAATCCCAGAGTGCTGTGCTGTTTACAGAATT"
    "CAGGATGGAGAGAAGAAACCAATTGGTTGGGACACTGATATTTCCTGGCTTACTGGAGAA"
    "GAATTGCATGTGGAAGTGTTGGAGAATGTTCCACTTACAACACACAACTTTGTACGAAAA"
    "ACGTTTTTCACCTTAGCATTTTGTGACTTTTGTCGAAAGCTGCTTTTCCAGGGTTTCCGC"
    "TGTCAAACATGTGGTTATAAATTTCACCAGCGTTGTAGTACAGAAGTTCCACTGATGTGT"
    "GTTAATTATGACCAACTTGATTTGCTGTTTGTCTCCAAGTTCTTTGAACACCACCCAATA"
    "CCACAGGAAGAGGCGTCCTTAGCAGAGACTGCCCTAACATCTGGATCATCCCCTTCCGCA"
    "CCCGCCTCGGACTCTATTGGGCCCCAAATTCTCACCAGTCCGTCTCCTTCAAAATCCATT"
    "CCAATTCCACAGCCCTTCCGACCAGCAGATGAAGATCATCGAAATCAATTTGGGCAACGA"
    "GACCGATCCTCATCAGCTCCCAATGTGCATATAAACACAATAGAACCTGTCAATATTGAT"
    "GACTTGATTAGAGACCAAGGATTTCGTGGTGATGGAGGATCAACCACAGGTTTGTCTGCT"
    "ACCCCCCCTGCCTCATTACCTGGCTCACTAACTAACGTGAAAGCCTTACAGAAATCTCCA"
    "GGACCTCAGCGAGAAAGGAAGTCATCTTCATCCTCAGAAGACAGGAATCGAATGAAAACA"
    "CTTGGTAGACGGGACTCGAGTGATGATTGGGAGATTCCTGATGGGCAGATTACAGTGGGA"
    "CAAAGAATTGGATCTGGATCATTTGGAACAGTCTACAAGGGAAAGTGGCATGGTGATGTG"
    "GCAGTGAAAATGTTGAATGTGACAGCACCTACACCTCAGCAGTTACAAGCCTTCAAAAAT"
    "GAAGTAGGAGTACTCAGGAAAACACGACATGTGAATATCCTACTCTTCATGGGCTATTCC"
    "ACAAAGCCACAACTGGCTATTGTTACCCAGTGGTGTGAGGGCTCCAGCTTGTATCACCAT"
    "CTCCATATCATTGAGACCAAATTTGAGATGATCAAACTTATAGATATTGCACGACAGACT"
    "GCACAGGGCATGGATTACTTACACGCCAAGTCAATCATCCACAGAGACCTCAAGAGTAAT"
    "AATATATTTCTTCATGAAGACCTCACAGTAAAAATAGGTGATTTTGGTCTAGCTACAGTG"
    "AAATCTCGATGGAGTGGGTCCCATCAGTTTGAACAGTTGTCTGGATCCATTTTGTGGATG"
    "GCACCAGAAGTCATCAGAATGCAAGATAAAAATCCATACAGCTTTCAGTCAGATGTATAT"
    "GCATTTGGAATTGTTCTGTATGAATTGATGACTGGACAGTTACCTTATTCAAACATCAAC"
    "AACAGGGACCAGATAATTTTTATGGTGGGACGAGGATACCTGTCTCCAGATCTCAGTAAG"
    "GTACGGAGTAACTGTCCAAAAGCCATGAAGAGATTAATGGCAGAGTGCCTCAAAAAGAAA"
    "AGAGATGAGAGACCACTCTTTCCCCAAATTCTCGCCTCTATTGAGCTGCTGGCCCGCTCA"
    "TTGCCAAAAATTCACCGCAGTGCATCAGAACCCTCCTTGAATCGGGCTGGTTTCCAAACA"
    "GAGGATTTTAGTCTATATGCTTGTGCTTCTCCAAAAACACCCATCCAGGCAGGGGGATAT"
    "GGTGCGTTTCCTGTCCACTGA"
)

BRAF_HOTSPOTS: Dict[int, str] = {
    599: "GTG",  # codon 600 (Val) - V600E site (GTG -> GAG)
}


# ---------------------------------------------------------------------------
# Import-time invariants. These run at module import and crash loudly
# if anyone edits the sequences above. The crashes are catastrophic on
# purpose: a corrupted reference CDS silently misclassifies every
# mutation downstream, which would invalidate patent-evidence demos.
# ---------------------------------------------------------------------------

def _assert_codon(seq: str, codon_1indexed: int, expected: str, gene: str) -> None:
    pos = (codon_1indexed - 1) * 3
    actual = seq[pos:pos + 3]
    assert actual == expected, (
        f"{gene} codon {codon_1indexed}: expected {expected}, got {actual}. "
        f"reference_cds.py is corrupted; do not file patent."
    )


def _assert_no_premature_stop(seq: str, gene: str, up_to_codon: int) -> None:
    """Assert no in-frame stop codon in codons 1..up_to_codon (1-indexed,
    inclusive). The stop codon at position up_to_codon+1 (the intended
    terminus) is not checked."""
    for i in range(up_to_codon):
        codon = seq[i * 3 : i * 3 + 3]
        assert codon not in ("TAA", "TAG", "TGA"), (
            f"{gene} has premature stop {codon} at codon {i+1}; "
            f"reference is broken."
        )


# KRAS: NM_004985.5, 188 aa + stop, codon 12 = GGT, codon 13 = GGC
_assert_codon(KRAS_CDS, 1, "ATG", "KRAS")
_assert_codon(KRAS_CDS, 12, "GGT", "KRAS")
_assert_codon(KRAS_CDS, 13, "GGC", "KRAS")
_assert_codon(KRAS_CDS, 189, "TAA", "KRAS")  # stop at 189 (= 188 aa + stop)
_assert_no_premature_stop(KRAS_CDS, "KRAS", up_to_codon=188)
assert len(KRAS_CDS) == 567, f"KRAS_CDS length {len(KRAS_CDS)}; expected 567"

# TP53: NM_000546.6, 393 aa + stop, codon 175 = CGC, codon 248 = CGG
_assert_codon(TP53_CDS, 1, "ATG", "TP53")
_assert_codon(TP53_CDS, 175, "CGC", "TP53")
_assert_codon(TP53_CDS, 248, "CGG", "TP53")
_assert_codon(TP53_CDS, 394, "TGA", "TP53")  # stop
_assert_no_premature_stop(TP53_CDS, "TP53", up_to_codon=393)
assert len(TP53_CDS) == 1182, f"TP53_CDS length {len(TP53_CDS)}; expected 1182"

# BRAF: NM_004333.6, 766 aa + stop, codon 600 = GTG
_assert_codon(BRAF_CDS, 1, "ATG", "BRAF")
_assert_codon(BRAF_CDS, 600, "GTG", "BRAF")
_assert_codon(BRAF_CDS, 767, "TGA", "BRAF")  # stop
_assert_no_premature_stop(BRAF_CDS, "BRAF", up_to_codon=766)
assert len(BRAF_CDS) == 2301, f"BRAF_CDS length {len(BRAF_CDS)}; expected 2301"


__all__ = [
    "KRAS_CDS", "KRAS_HOTSPOTS",
    "TP53_CDS", "TP53_HOTSPOTS",
    "BRAF_CDS", "BRAF_HOTSPOTS",
]
