"""
RFdiffusion NIM Client
======================

Generate novel protein binder structures using diffusion models.
Given a target protein PDB, generates a binder that fits the target surface.
"""

import logging
from dataclasses import dataclass
from typing import Optional

from .client import NIMClient

logger = logging.getLogger(__name__)

ENDPOINT = "ipd/rfdiffusion/generate"


@dataclass
class GeneratedBinder:
    """A protein binder structure generated by RFdiffusion."""
    pdb_data: str  # Full PDB file content
    target_residues: str  # Which residues were targeted
    binder_length: str  # Requested binder length range


class RFdiffusionClient(NIMClient):
    """Client for RFdiffusion protein binder design NIM.

    RFdiffusion uses diffusion models to generate novel protein structures
    that bind to a target protein. The output is a PDB file containing
    the designed binder.

    Example:
        client = RFdiffusionClient()
        pdb_data = open("target.pdb").read()
        binder = client.design_binder(pdb_data, "A19-42", "70-100")
        with open("binder.pdb", "w") as f:
            f.write(binder.pdb_data)
    """

    def design_binder(self, target_pdb: str, target_residues: str,
                      binder_length: str = "70-100") -> GeneratedBinder:
        """Design a protein binder for a target.

        Args:
            target_pdb: PDB file content of the target protein.
            target_residues: Residue range to target (e.g., "A19-42").
            binder_length: Length range for the binder (e.g., "70-100").

        Returns:
            GeneratedBinder with the designed PDB structure.
        """
        contigs = f"{target_residues}/0 {binder_length}"
        result = self._post(ENDPOINT, {
            "input_pdb": target_pdb,
            "contigs": contigs,
        }, timeout=300)

        binder = GeneratedBinder(
            pdb_data=result["output_pdb"],
            target_residues=target_residues,
            binder_length=binder_length,
        )
        logger.info(f"Generated binder for residues {target_residues}")
        return binder

    def design_binder_from_file(self, pdb_path: str, target_residues: str,
                                binder_length: str = "70-100") -> GeneratedBinder:
        """Design a binder from a PDB file path.

        Convenience method that reads the PDB file first.
        """
        with open(pdb_path) as f:
            pdb_data = f.read()
        return self.design_binder(pdb_data, target_residues, binder_length)
